services:
  blog:
    image: ccr.ccs.tencentyun.com/sumery/blog:latest # 这里需要替换成你的镜像名
    container_name: blog
    build:
      context: .
      dockerfile: .
      target: final
    ports:
      - '80:80'
      - '443:443'
      - '443:443/udp'
    restart: on-failure:4 # 重启策略，最多重启n次
    volumes:
      - /home/docker/blog/conf:/etc/nginx/conf.d
      - /home/docker/blog/ssl:/etc/nginx/ssl:ro
